// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9cWtIG6qorsRPFe-GDy6CmjmGTg3gk-U',
    appId: '1:1021261548883:web:4505271382bc0e5e5165a6',
    messagingSenderId: '1021261548883',
    projectId: 'wallpaper-app-ff55e',
    authDomain: 'wallpaper-app-ff55e.firebaseapp.com',
    storageBucket: 'wallpaper-app-ff55e.appspot.com',
    measurementId: 'G-LBVLTDK0B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrRgMIWwRpWMAyOaYSX-m7wHOr7GNESW4',
    appId: '1:1021261548883:android:bb7a1a255e18e3d65165a6',
    messagingSenderId: '1021261548883',
    projectId: 'wallpaper-app-ff55e',
    storageBucket: 'wallpaper-app-ff55e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz5kh7c9dIx4E87Lqd29z6n5cT-CSCrdQ',
    appId: '1:1021261548883:ios:de073c24164633d25165a6',
    messagingSenderId: '1021261548883',
    projectId: 'wallpaper-app-ff55e',
    storageBucket: 'wallpaper-app-ff55e.appspot.com',
    iosClientId: '1021261548883-5u4467k3i7m7p7iup2eiqleukvou0dpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz5kh7c9dIx4E87Lqd29z6n5cT-CSCrdQ',
    appId: '1:1021261548883:ios:de073c24164633d25165a6',
    messagingSenderId: '1021261548883',
    projectId: 'wallpaper-app-ff55e',
    storageBucket: 'wallpaper-app-ff55e.appspot.com',
    iosClientId: '1021261548883-5u4467k3i7m7p7iup2eiqleukvou0dpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperApp',
  );
}
